AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template for using create an EC-2 instance and also create a new security group. 

Parameters:
  KeyName:
    Description: The Ec2 Key Pair to allow SSH access to the instance. Hello Huseyin. 
    Type: AWS::EC2::KeyPair::KeyName

  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  
Mappings:
  RegionMap: 
    us-east-1: 
      "HVM64": "ami-02354e95b39ca8dec"
    us-west-1: 
      "HVM64": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "HVM64": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "HVM64": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "HVM64": "ami-06cd52961ce9f0d85"
  
Resources:
  MyFirstInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap 
        - RegionMap
        - !Ref "AWS::Region"
        - HVM64
      InstanceType: !Ref InstanceTypeParameter
      KeyName:
        Ref : KeyName
      SecurityGroups:
        - !Ref MyFirstSecurityGroup
      Tags:
        - Key: "Name"
          Value: "My First Instance"
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user/
        wget https://raw.githubusercontent.com/huseyin-yigit/working_group/master/001-Project-Tc-ID-SG/app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/huseyin-yigit/working_group/master/001-Project-Tc-ID-SG/templates/index.html
        wget https://raw.githubusercontent.com/huseyin-yigit/working_group/master/001-Project-Tc-ID-SG/templates/result.html
        cd ..
        python3 app.py
        
  MyFirstSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH and HTTP port access via port 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "My First Security Group"
  
Outputs:
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
        - MyFirstInstance
        - PublicDnsName